### PR TITLE
[Onyx-702] Fix BeamCoder to catch CoderException and throw IOException instead

### LINKED ISSUE #702: Fix all coders to finally throw IOException
Currently, all coders are implementing our `Coder` interface, which throws `IOException` in its `encode()` and `decode()` methods. We can fix other coders to wrap exception to `IOException`.

### PR DESCRIPTION
**Pull request by skystar-p**
Closes #702 

* Fix `BeamCoder`'s `encode()` and `decode()` methods to catch `CoderException`

### CODE REVIEW

File: compiler/frontend/src/main/java/edu/snu/onyx/compiler/frontend/beam/coder/BeamCoder.java [hunk 1]
```diff
@@ -38,12 +39,20 @@ public BeamCoder(final org.apache.beam.sdk.coders.Coder<T> beamCoder) {
 
   @Override
   public void encode(final T value, final OutputStream outStream) throws IOException {
-    beamCoder.encode(value, outStream);
+    try {
+      beamCoder.encode(value, outStream);
+    } catch (CoderException e) {
```
Comment (seojangho) [inline compiler/frontend/src/main/java/edu/snu/onyx/compiler/frontend/beam/coder/BeamCoder.java]: `final CoderException e`

File: compiler/frontend/src/main/java/edu/snu/onyx/compiler/frontend/beam/coder/BeamCoder.java [hunk 2]
```diff
@@ -38,12 +39,20 @@ public BeamCoder(final org.apache.beam.sdk.coders.Coder<T> beamCoder) {
...
+      throw new IOException(e);
+    }
   }
 
   @Override
   public T decode(final InputStream inStream) throws IOException {
-    return beamCoder.decode(inStream);
+    try {
+      return beamCoder.decode(inStream);
+    } catch (CoderException e) {
```
Comment (seojangho) [inline compiler/frontend/src/main/java/edu/snu/onyx/compiler/frontend/beam/coder/BeamCoder.java]: Same here.

File: runtime/executor/src/main/java/edu/snu/onyx/runtime/executor/data/blocktransfer/BlockInputStream.java [hunk 3]
```diff
@@ -141,12 +140,7 @@ void startDecodingThreadIfNeeded() {
         // already ended. But elementQueue should be non-empty to process latter task, so decode() should be
         // invoked in spite of the end of stream.
         if (byteBufInputStream.isEnded()) {
-          try {
-            elementQueue.add(coder.decode(byteBufInputStream));
-            // In this case, exception raised in coder can be ignored
-          } catch (final CoderException e) {
-            LOG.warn("CoderException was thrown when invoke decode() on end of stream, but can be ignored");
-          }
+          elementQueue.add(coder.decode(byteBufInputStream));
```
Comment (seojangho) [inline runtime/executor/src/main/java/edu/snu/onyx/runtime/executor/data/blocktransfer/BlockInputStream.java]: How about catching `IOException` here?

Comment (seojangho) [reply runtime/executor/src/main/java/edu/snu/onyx/runtime/executor/data/blocktransfer/BlockInputStream.java]: Let me know your opinion.
