### PR TITLE
[Onyx-633, 658, 285] Refactor SchedulingPolicy

### LINKED ISSUE #285: Make SchedulerRunner failure reportable
At now, when `SchedulerRunner` experiences a failure during assigning task group, it just leaves exception message and die.
In this case, the Scheduler can not know this failure.
So, we need to make `SchedulerRunner` to can report failure.

### LINKED ISSUE #633: Prevent the "Not Yet" Executing TaskGroups of A Removed Executor from Being Lost
The calls to `attemptSchedule()` and `onTaskGroupScheduled()` of `SchedulingPolicy` are non-atomic.

This results in a `TaskGroup` being lost when:
1. `attemptSchedule` is called, successfully with an executor picked
2. the picked executor is removed
3. `onTaskGroupScheduled` is called but the executor has been removed

### LINKED ISSUE #658: Refactor SchedulingPolicy
We have a few changes we would like to make to the current implementation:
- Make `attemptSchedule()` and `onTaskGroupScheduled()` atomic
- Change a few possible synchronization issues within `RoundRobinSchedulingPolicy`

### PR DESCRIPTION
**Pull request by jooykim**
Resolves #633 .
Resolves #658 .
Resolves #285 .

This PR:

- Refactors the attemptSchedule() and onTaskGroupScheduled() APIs into a single atomic operation.

- Prevents TaskGroups from being lost due to synchronization issues upon failures.

- Fails the job as soon as the `SchedulerRunner` thread faces a runtime exception.

### CODE REVIEW

File: runtime/master/src/main/java/edu/snu/onyx/runtime/master/scheduler/RoundRobinSchedulingPolicy.java [hunk 1]
```diff
@@ -98,23 +100,23 @@ public long getScheduleTimeoutMs() {
...
     lock.lock();
     try {
       final String containerType = scheduledTaskGroup.getTaskGroup().getContainerType();
       initializeContainerTypeIfAbsent(containerType);
 
-      final Optional<String> executorId = selectExecutorByRR(containerType);
+      Optional<String> executorId = selectExecutorByRR(containerType);
       if (!executorId.isPresent()) { // If there is no available executor to schedule this task group now,
         final boolean executorAvailable =
             conditionByContainerType.get(containerType).await(scheduleTimeoutMs, TimeUnit.MILLISECONDS);
```
Comment (johnyangk) [inline runtime/master/src/main/java/edu/snu/onyx/runtime/master/scheduler/RoundRobinSchedulingPolicy.java]: Add a pointer to #696?

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java [hunk 2]
```diff
@@ -181,11 +168,42 @@ public void testContainerRemoval() throws Exception {
...
+    }
+    return new PhysicalPlan("TestPlan", physicalDAG, physicalPlanGenerator.getTaskIRVertexMap());
+  }
 
-    final PhysicalPlan plan = new PhysicalPlan("TestPlan", physicalDAG, physicalPlanGenerator.getTaskIRVertexMap());
+  /**
+   * Tests fault tolerance after a container removal.
+   */
+  @Test(timeout=10000)
+  public void testContainerRemoval() throws Exception {
```
Comment (johnyangk) [inline tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java]: Can you add a multi-threaded test that fails with the previous code, and passes with this PR?

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java [hunk 3]
```diff
@@ -181,11 +168,42 @@ public void testContainerRemoval() throws Exception {
...
-        new TestPolicy(), "");
-    final DAG<PhysicalStage, PhysicalStageEdge> physicalDAG = irDAG.convert(physicalPlanGenerator);
+    DAG<IRVertex, IREdge> irDAG;
+    DAG<PhysicalStage, PhysicalStageEdge> physicalDAG = null;
+    try {
+      irDAG = CompiletimeOptimizer.optimize(irDAGBuilder.buildWithoutSourceSinkCheck(),
+          new TestPolicy(), "");
+      physicalDAG = irDAG.convert(physicalPlanGenerator);
+    } catch (Exception e) {
+      e.printStackTrace();
```
Comment (johnyangk) [inline tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java]: Throw an exception to fail the test.

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java [hunk 4]
```diff
@@ -103,45 +100,35 @@ public void setUp() throws Exception {
...
-    physicalPlanGenerator = injector.getInstance(PhysicalPlanGenerator.class);
+    executorRepresenterMap.keySet().forEach(executorId -> scheduler.onExecutorAdded(executorId));
   }
 
-  /**
-   * Tests fault tolerance after a container removal.
-   */
-  @Test(timeout=10000)
-  public void testContainerRemoval() throws Exception {
+  private PhysicalPlan buildPlan() {
```
Comment (johnyangk) [inline tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java]: In L154, replace `new DoTransform(null, null)` with `t`.

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java [hunk 5]
```diff
@@ -181,11 +168,42 @@ public void testContainerRemoval() throws Exception {
     final IREdge e4 = new IREdge(DataCommunicationPatternProperty.Value.OneToOne, v4, v5, Coder.DUMMY_CODER);
     irDAGBuilder.connectVertices(e4);
 
-    final DAG<IRVertex, IREdge> irDAG = CompiletimeOptimizer.optimize(irDAGBuilder.buildWithoutSourceSinkCheck(),
-        new TestPolicy(), "");
-    final DAG<PhysicalStage, PhysicalStageEdge> physicalDAG = irDAG.convert(physicalPlanGenerator);
+    DAG<IRVertex, IREdge> irDAG;
+    DAG<PhysicalStage, PhysicalStageEdge> physicalDAG = null;
+    try {
```
Comment (johnyangk) [inline tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java]: This can be removed and `physicalDAG` can be assigned to a non-null value,  if `buildPlan()` throws an Exception.

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java [hunk 6]
```diff
@@ -196,18 +214,14 @@ public void testContainerRemoval() throws Exception {
...
-        RuntimeTestUtil.mockSchedulerRunner(pendingTaskGroupQueue, schedulingPolicy, false);
+        RuntimeTestUtil.mockSchedulerRunner(pendingTaskGroupQueue, schedulingPolicy, jobStateManager, false);
         assertTrue(pendingTaskGroupQueue.isEmpty());
-        stage.getTaskGroupList().forEach(taskGroup -> {
-          jobStateManager.onTaskGroupStateChanged(taskGroup, TaskGroupState.State.EXECUTING);
+        stage.getTaskGroupList().forEach(taskGroup ->
           RuntimeTestUtil.sendTaskGroupStateEventToScheduler(scheduler, containerManager,
-              taskGroup.getTaskGroupId(), TaskGroupState.State.COMPLETE, 1, null);
-            });
+              taskGroup.getTaskGroupId(), TaskGroupState.State.COMPLETE, 1, null));
```
Comment (johnyangk) [inline tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java]: Can you create another `sendTaskGroupStateEventToScheduler()` without the `TaskGroupState.RecoverableFailureCause cause)` argument such that this line can be replaced with the following line?

```java
taskGroup.getTaskGroupId(), TaskGroupState.State.COMPLETE, 1) // no null here
```

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java [hunk 7]
```diff
@@ -217,28 +231,26 @@ public void testContainerRemoval() throws Exception {
...
-        RuntimeTestUtil.mockSchedulerRunner(pendingTaskGroupQueue, schedulingPolicy, false);
+        RuntimeTestUtil.mockSchedulerRunner(pendingTaskGroupQueue, schedulingPolicy, jobStateManager, false);
         assertTrue(pendingTaskGroupQueue.isEmpty());
         stage.getTaskGroupList().forEach(taskGroup -> {
-          final Enum taskGroupState =
-              jobStateManager.getTaskGroupState(taskGroup.getTaskGroupId()).getStateMachine().getCurrentState();
-          if (taskGroupState == TaskGroupState.State.READY) {
-            jobStateManager.onTaskGroupStateChanged(taskGroup, TaskGroupState.State.EXECUTING);
-          }
+//          final Enum taskGroupState =
```
Comment (johnyangk) [inline tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java]: Remove L237-L241.

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/SingleTaskGroupQueueTest.java [hunk 8]
```diff
@@ -110,6 +112,8 @@ public void testPushPriority() throws Exception {
 
     final CountDownLatch countDownLatch = new CountDownLatch(2);
 
+    final AtomicBoolean passed = new AtomicBoolean(true);
+
     // This mimics Batch Scheduler's behavior
     executorService.execute(() -> {
```
Comment (johnyangk) [inline tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/SingleTaskGroupQueueTest.java]: Instead of `AtomicBoolean passed`, can you use `Callable` with a timeout?

```java
@timeout
void test throws Exception {
  futureList = submitToExecutorService(callableList)
  
  // throws ExecutionException if the callable throws an error 
  // indefinite blocking is caught by the timeout
  futureList.forEach(future -> future.get());
}
```

Ditto on `testPullPriority()`, `testPushRemoveAndAddStageDependency()`, and `testContainerTypeAwareness()` to fail the tests on errors.

File: runtime/master/src/main/java/edu/snu/onyx/runtime/master/scheduler/RoundRobinSchedulingPolicy.java [hunk 9]
```diff
@@ -213,30 +246,29 @@ public void onExecutorAdded(final String executorId) {
...
+      print("onExecutorRemoved After", containerType);
+
       return Collections.unmodifiableSet(executor.getRunningTaskGroups());
     } finally {
       lock.unlock();
     }
   }
 
+  private void print(final String calledMethod, final String containerType) {
+    LOG.info(calledMethod);
```
[the remark this answers is not in the document]
Comment (jooykim) [reply runtime/master/src/main/java/edu/snu/onyx/runtime/master/scheduler/RoundRobinSchedulingPolicy.java]: This method was for debugging purposes, I'm deleting it.

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java (hunk 2 above)
Comment (jooykim) [reply tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/FaultToleranceTest.java]: testTaskGroupReexecutionForFailure() fails with the previous code (occasionally) and passes with this PR.

File: tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/SingleTaskGroupQueueTest.java (hunk 8 above)
Comment (jooykim) [reply tests/src/test/java/edu/snu/onyx/tests/runtime/master/scheduler/SingleTaskGroupQueueTest.java]: I'm actually working on this in #683 :)

**Comment by jooykim** [comment]
@johnyangk Thanks for the review :) I've addressed your first round of comments.

**Comment by johnyangk** [comment]
@jooykim Thanks. LGTM. Please fix the failed tests and merge.
