### PR TITLE
[Onyx-695] Make WriteFiles to be executed properly

### LINKED ISSUE #695: Fail to write output at test
When running tests, sometimes it writes output correctly, but sometimes just writes output to the temporary file and cannot rename it into the actual output file name.

Me and @seojangho analyzed this issue and found an expected reason of this symptom.

The final DAG of this task is like the following image:
dag
You can see `VoidCoder` on the edge between of `TaskGroup-1` and `TaskGroup-4`.

In successive case of test, the log was:
```
./driver/driver.stdout:2018-01-03 16:08:16,362 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-1 to Executor-2
./driver/driver.stdout:2018-01-03 16:08:16,486 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-2 to Executor-1
./driver/driver.stdout:2018-01-03 16:08:17,702 INFO edu.snu.onyx.runtime.master.scheduler.BatchSingleJobScheduler scheduleStage pool-2-thread-1 Scheduling TaskGroup-3
./driver/driver.stdout:2018-01-03 16:08:17,704 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-3 to Executor-1
./driver/driver.stdout:2018-01-03 16:08:17,995 INFO edu.snu.onyx.runtime.master.scheduler.BatchSingleJobScheduler scheduleStage pool-2-thread-1 Scheduling TaskGroup-4
./driver/driver.stdout:2018-01-03 16:08:17,996 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-4 to Executor-2
```

otherwise, log of failing case was:
```
./driver/driver.stdout:2018-01-03 16:09:21,182 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-1 to Executor-1
./driver/driver.stdout:2018-01-03 16:09:21,312 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-2 to Executor-2
./driver/driver.stdout:2018-01-03 16:09:22,469 INFO edu.snu.onyx.runtime.master.scheduler.BatchSingleJobScheduler scheduleStage pool-2-thread-1 Scheduling TaskGroup-3
./driver/driver.stdout:2018-01-03 16:09:22,479 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-3 to Executor-1
./driver/driver.stdout:2018-01-03 16:09:23,455 INFO edu.snu.onyx.runtime.master.scheduler.BatchSingleJobScheduler scheduleStage pool-2-thread-1 Scheduling TaskGroup-4
./driver/driver.stdout:2018-01-03 16:09:23,457 INFO edu.snu.onyx.runtime.master.scheduler.RoundRobinSchedulingPolicy onTaskGroupScheduled pool-1-thread-1 Scheduling TaskGroup-4 to Executor-3
```

We found that when `TaskGroup-1` and `TaskGroup-4` was scheduled on different executor, it couldn't initiate `TaskGroup-4`(task about writing output).

It seems `VoidCoder` edge is the reason of this issue.

### PR DESCRIPTION
**Pull request by skystar-p**
Closes #695 

* Fixed `startDecodeThreadIfNeeded` to invoke `coder.decode()` at least once.
* Resolve race condition between starting decoding thread and closing `ByteBufInputStream`.
* Fixed `ClosableBlockingIterable` to allow `null` element.

### CODE REVIEW

**Comment by wonook** [comment]
!rebuild

File: runtime/executor/src/main/java/edu/snu/onyx/runtime/executor/data/blocktransfer/BlockInputStream.java [hunk 1]
```diff
@@ -136,6 +137,13 @@ void startDecodingThreadIfNeeded() {
     executorService.submit(() -> {
       try {
         final long startTime = System.currentTimeMillis();
+        if (byteBufInputStream.isEnded()) {
```
Comment (seojangho) [inline runtime/executor/src/main/java/edu/snu/onyx/runtime/executor/data/blocktransfer/BlockInputStream.java]: Can you kindly add in-line comments above this line to clarify the reason this block is needed?
